cache: bundler
language: ruby
rvm:
  - "2.6"
  - "2.7"
  - "3.0"
  #- jruby-19mode # Due to https://github.com/jruby/jruby/issues/2599
jobs:
  allow_failures:
    - "2.7" # bundler version incompatibility, fix later...
install:
  - bundle install --retry=3
script:
  - bundle exec rake
